### ISSUE TITLE
Can jqapi generate offline docs for QUnit?

### ISSUE THREAD

**Issue by qris** [jqapi/jqapi#17]
The API documentation for QUnit is also available online, in a similar format, from https://github.com/jquery/api.qunitjs.com.

I tried to modify JQApi to download and generate these docs instead, but the `thor docs:generate` command fails with an error:

```
/home/chris/aptivate/long/bmo/jqapi/tasks/documentation.thor:124:in `[]': can't convert String into Integer (TypeError)
from /home/chris/aptivate/long/bmo/jqapi/tasks/documentation.thor:124:in `block in compose_wrapper'
from /home/chris/aptivate/long/bmo/jqapi/tasks/documentation.thor:123:in `each'
from /home/chris/aptivate/long/bmo/jqapi/tasks/documentation.thor:123:in `compose_wrapper'
from /home/chris/aptivate/long/bmo/jqapi/tasks/documentation.thor:90:in `block in parse_xml_entries'
from /home/chris/aptivate/long/bmo/jqapi/tasks/documentation.thor:58:in `each'
from /home/chris/aptivate/long/bmo/jqapi/tasks/documentation.thor:58:in `parse_xml_entries'
from /home/chris/aptivate/long/bmo/jqapi/tasks/documentation.thor:40:in `generate'
```

I'm not really sure why it's trying to convert a string to an integer:

```
entry['category'].each do |cat|                       # simplify the categories array
  content[:categories].push cat['slug']               # add value to simple array
end
```

It looks like the problem is `cat['slug']`. Perhaps `cat` is an array instead of a hash, so `slug` is not a valid index into it? But I don't understand why `cat` would be an array when processing these docs, and a hash when processing the JQuery docs? I think it comes from the XML parser, so why is it different?

Thanks in advance for your help!

**Comment by mustardamus** [comment]
jQAPI V3 is now released. Closing this issue in favor of it. Thanks.
