### ISSUE TITLE
404 @jqapi.air

### ISSUE THREAD

**Issue by FlashJunior** [jqapi/jqapi#19]
can't download Air Version @ http://jqapi.com/jqapi.air

**Comment by FlashJunior** [comment]
any update?

**Comment by enigmatic-user** [comment]
I'd be interested, too.  ;)

**Comment by FlashJunior** [comment]
@enigmatic-user wenn du OSX verwendest kann ich dir die jQAPI.app senden. Die kannst einfach in den Application Order schieben. Email me: fj@flashjunior.ch

**Comment by enigmatic-user** [comment]
@FlashJunior Vielen Dank, aber leider bin ich auf einem Windows-System unterwegs. Ich habe auch eine Air-Version von jQAPI, mit der ich arbeiten kann, nur halt nicht die neueste.

**Comment by mustardamus** [comment]
jQAPI V3 is now released. Closing this issue in favor of it. Thanks.
