### ISSUE TITLE
Please, push all tags

### ISSUE THREAD

**Issue by marcelometal** [jqapi/jqapi#20]
Could you please push all tags?

Cheers.

**Comment by mustardamus** [comment]
jQAPI V3 is now released. Closing this issue in favor of it. Thanks.

**Comment by marcelometal** [comment]
Hi @mustardamus , where are the tags?!

**Comment by mustardamus** [comment]
Hi @marcelometal , what do you mean by tags?

**Comment by marcelometal** [comment]
[Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging)!

 there is no tags here: https://github.com/jqapi/jqapi/tags

**Comment by mustardamus** [comment]
So far, I haven't used tags for the jqapi repository. I'll begin tagging the next releases. Thanks.
