### ISSUE TITLE
SSL cert

### ISSUE THREAD

**Issue by squelchdesign** [jqapi/jqapi#27]
Hey, the site's certificate has been replaced with a self-signed cert which violates the HSTS policy for the site.

As per my last ticket, if there's anything I can do to help just let me know.

**Comment by mustardamus** [comment]
Hi Matt,

sorry for the late reply, I  am on a bike trip and finally have time and internet access to deal with it. The MediaTemple sponsoring ended, so the server was re-assigned (I guess).

I've moved jQAPI to Netlify for now. Could take a bit for the DNS to propagate.

Thanks for letting me know!
